### ISSUE TITLE
AppImage does not run on RHEL 7.7

### ISSUE THREAD

**Issue by asimasiddiqui** [ibm-apiconnect/test-and-monitor#25]
Downloaded and made executable. Launching from command line shows

This option is not available. Please see --help for all possible usages.

**Comment by taha-ben-masaud** [comment]
Thanks @asimX for reporting this. We'll look into this and get back to you as soon as we can.

**Comment by taha-ben-masaud** [comment]
@asimX what version are trying to execute?

Also, did you try installing the app instead?

**Comment by asimX** [comment]
I downloaded and tried to run the executable. V1.0.1. Has this been tested on RHEL 7.7?

**Comment by taha-ben-masaud** [comment]
We tested the executable on RHEL 7.7 and it works fine.

What I can suggest is:

1. Ensure the binaries are _executable_
2. Try to run the executable using the terminal & mouse clicks.
3. Try to delete old app data; I'm not entirely sure where in RHEL that'd be. Note this will delete all your saved data.

**Comment by abutch3r** [comment]
It has been decided to remove the app as we are unable to continue its development
