### ISSUE TITLE
Automates  the CI/CD Process

### ISSUE THREAD

**Issue by prabago** [ibm-apiconnect/test-and-monitor#27]
Hi,
Is it possible to automate the tests through Jenkins?

Thanks in advance!

Regards!

**Comment by geraintwjones** [comment]
Hi. Right now we don't have CI/CD capabilities. It is in our list of features to add, but it's not something we'll be adding in the short term.

**Comment by lvnar** [comment]
Hi. Almost one year later, I'd like to know if there is any project you may thinking to include the CI/CD integrations or any API to launch manually the Testing.

Regards!

**Comment by jameskhedley** [comment]
Hi! I don't think it's documented yet but I believe this is working now.

If you hit the top right cog button after logging in, you should see API Hoooks and Keys. If you create both a hook and a key, noting them down as you do so (the API key secret has to be copied from the dialogue, a small bug), you should be able to list tests thusly (replace the key, secret and hook values):

```
curl \
-H "X-API-Key:7d0f3ae7-f5d1-4ff1-ae11-d9e939a00ea8" \
-H "X-API-Secret:636f55de65b02e738b741b2de98df4c88297fe216533abc102b08aa4c8dac1ff" \
https://us-east.apitest.apiconnect.ibmcloud.com/app/api/rest/v1/14b72f55-1f4e-4837-81f9-e156ece38117757/tests
```

You can then run *all* tests such as:

```curl \
-X POST \
-H "X-API-Key:7d0f3ae7-f5d1-4ff1-ae11-d9e939a00ea8" \
-H "X-API-Secret:636f55de65b02e738b741b2de98df4c88297fe216533abc102b08aa4c8dac1ff" \
-H "Content-Type:application/json" \
-d "" \
https://us-east.apitest.apiconnect.ibmcloud.com/app/api/rest/v1/14b72f55-1f4e-4837-81f9-e156ece38117757/tests/run
```

Or a *single* test by getting it's ID from the list and calling the hook like this:

```curl \
-X POST
-H X-API-Key:7d0f3ae7-f5d1-4ff1-ae11-d9e939a00ea8 \
-H X-API-Secret:636f55de65b02e738b741b2de98df4c88297fe216533abc102b08aa4c8dac1ff \
-H Content-Type:application/json \
-d "{options:{allAssertions:true}}" \
https://us-east.apitest.apiconnect.ibmcloud.com/app/api/rest/v1/14b72f55-1f4e-4837-81f9-e156ece38117757/tests/5e3313a6aad00f004637d3eb/run```

Hope that helps! Please let us know how you get on with the new feature.
