### ISSUE TITLE
Undo does not work

### ISSUE THREAD

**Issue by jduffy3** [ibm-apiconnect/test-and-monitor#34]
I was using the Desktop client,
imported my Postman collection, opened a Request and clicked Options -> Clear.

This cleared my request but when I clicked Undo my request was not restored.

**Comment by taha-ben-masaud** [comment]
I assume the app couldn't handle an internal error and subsequently showed you a view where you were given the option to _undo_?

**Comment by jduffy3** [comment]
No - I cleared a request and clicked Edit -> Undo.

**Comment by abutch3r** [comment]
We have made the decision to remove the app as we are unable to continue its development due to changes in priorities
