### ISSUE TITLE
Cookies are not persisted across requests

### ISSUE THREAD

**Issue by jduffy3** [ibm-apiconnect/test-and-monitor#36]
I have an App that requires the user authenticate via a REST URL.
The response includes a LtpaToken cookie that then needs to be included for each subsequent request otherwise, they will be redirected to Login.

Currently I don't see any option to allow me to set cookies for requests or that they are stored across requests (like in Postman)

**Comment by abutch3r** [comment]
We have made the decision to remove the app as we are unable to continue its development due to changes in priorities
