### ISSUE TITLE
404 on valid request

### ISSUE THREAD

**Issue by timroster** [ibm-apiconnect/test-and-monitor#4]
I am seeing intermittent 404 when using Test and Monitor to reach an IBM Cloud API Connect endpoint. There are no 404's in the analytics for the API so it looks like a problem with the request engine in Test and Monitor.

Here are the headers from a response with 404 http code:
```
Date	Tue, 19 Feb 2019 01:17:35 GMT
Content-Type	application/json
Transfer-Encoding	chunked
Connection	keep-alive
Set-Cookie	__cfduid=d46cd2aafcb82aaa39cbf23d32a4d57721550539054; expires=Wed, 19-Feb-20 01:17:34 GMT; path=/; domain=.apiconnect.appdomain.cloud; HttpOnly
Access-Control-Allow-Origin	*
Access-Control-Expose-Headers	APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID
X-Backside-Transport	FAIL FAIL
Expect-CT	max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server	cloudflare
CF-RAY	4ab4e505ac9f9fe4-IAD
```

**Comment by timroster** [comment]
Working requests always have the response header:
```
X-Backside-Transport	OK OK
```

**Comment by jameskhedley** [comment]
Probably a DataPower issue, we might be doing something it doesn't like, although if it's intermittent it could even be overutilisation.

https://developer.ibm.com/answers/questions/280011/getting-404-with-x-backside-transport-fail-fail-wh.html

**Comment by timroster** [comment]
As I can reproduce this with another API testing tool, it does look to be a DataPower / over-utilization issue rather than a problem with API Connect Test and Monitor (closing...)
