### ISSUE TITLE
Scheduling in the on-premise APIC Test & Monitor installation?

### ISSUE THREAD

**Issue by vvidovic** [ibm-apiconnect/test-and-monitor#46]
We noticed in our on-premise IBM API Connect installation Test & Monitoring tool doesn't have a "Schedule" action (as opposed to the Cloud version of the tool).

We are using the APIC version 10.0.2.0.

Is there a plan to include scheduling in the on-premise version of the tool?

Thanks.

**Comment by abutch3r** [comment]
@vvidovic It is on the roadmap for inclusion within APIC, but cannot give details of when.

It is possible to achieve a similar capability using the Hooks feature and having a pipeline like jenkins kick off the test cases and then handle in the case of failures, this gives more flexiblity given that the cloud offering only had email notifications. 

https://www.ibm.com/docs/en/api-connect/10.0.x?topic=aabtt-invoking-test-cases-from-jenkins-junit-result-format
