### ISSUE TITLE
What license is this available under?

### ISSUE THREAD

**Issue by No9** [ibm-apiconnect/test-and-monitor#5]
Congratulations on the release but it's not clear if it's an OSS project or not.

**Comment by taha-ben-masaud** [comment]
Thank you for having a look at our desktop release.

The license should be presented to users as the installation process begins. For your convenience, the app is under [International License Agreement for Non-Warranted Programs](http://www-03.ibm.com/software/sla/sladb.nsf/displaylis/2AEEA753FB4341FE852583CC00582B06?OpenDocument).

Hope this helps?

**Comment by abitrolly** [comment]
Because ILAN is not an OSI approved license, I tend to assume that it is not an OSS project - https://opensource.org/licenses/alphabetical

The source code for the desktop app is provided as a .tar.gz which is also strange considering that a lot of organization repositories here.

**Comment by geraintwjones** [comment]
I believe that thje source code that is bundled with the desktop app is in fact the source code for the developer portal website. I agree that this is not ideal, and we need to take steps to seperate them. I believe this is a side-effect of the fact that we've used the same repository for both.

**Comment by abitrolly** [comment]
There is no desktop app code in git repository, only the website.

**Comment by abitrolly** [comment]
If you're going to ask them properly open sourcing this work, then pointing at https://spdx.org/licenses/ may help as well.

**Comment by geraintwjones** [comment]
Closing this issue. We have no plans to open-source the desk top application.
