### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by joahnp** [ibm-apiconnect/test-and-monitor#50]
Please help with the security warning you receive when logging on.  Multiple users are having the same issue and our clock is correct.
 
<img width="1427" alt="api connect sec issue" src="https://user-images.githubusercontent.com/84515165/118989012-aebb5680-b94f-11eb-8120-2da94c4d07ad.png">

**Comment by joahnp** [comment]
![image](https://user-images.githubusercontent.com/84515165/118989356-f80ba600-b94f-11eb-8f7c-7e4fe44caefd.png)

**Comment by abutch3r** [comment]
It is recommend that you switch to https://apitest.us-east.apiconnect.cloud.ibm.com/app/ which is the now the primary URL for the application which does have a valid certificate. it is the same deployment as was hosted on the old URL
