### ISSUE TITLE
Postman collections don´t work

### ISSUE THREAD

**Issue by rubenfl5** [ibm-apiconnect/test-and-monitor#6]
We have tried to import the postman collections into the desktop application but it indicates a version or format bug. We have tested with the three versions that allows to export the collections in postman. This failure does not occur in the cloud application.

**Comment by rubenfl5** [comment]
Good afternoon, we discovered the error in importing the collections. We had divided the collections in subfolders ordered by type of operations, this produced the error of format. 
Another question has arisen, how can we place path parameters or query parameters in the URL of the request? It would be to make dynamic queries about the value of a field. Using the 'Params' button allows us to add the field and the value but what is placed behind the '?' symbol does not interpret it correctly. 
Thank you very much. Greetings.

**Comment by jahidzaynal** [comment]
Aha, yes we haven't covered collections with subfolders, sorry.
As for query params, can you elaborate on "what is placed behind the '?' symbol does not interpret it correctly" - the Params input pairs do allow you to add query params and values, and they do get sent as part of the request.

![queryParams](https://user-images.githubusercontent.com/48833800/55896658-b4fa7880-5bb6-11e9-831d-185a2b2e40cf.gif)

**Comment by rubenfl5** [comment]
Good afternoon, we tested the query parameters following the video you sent me and using a Postman mock server. The result has been satisfactory. 
Regarding the path parameters we have a problem. We create collections in Postman with path type dynamic variables (example: https://2a1d4042-c95e-47e4-8817-fe007bf2b146. mock. pstmn. io/catalog/cars/:id-cars) and define the value of the field according to the test we are going to perform and according to the answer we want to return (if we give value "01" to "id-cars" that returns one thing, if it is "02" that returns another answer). Is it possible to do it in any way?
We have only been able to perform the tests by putting the value directly into the url (https://2a1d4042-c95e-47e4-8817-fe007bf2b146. mock. pstmn. io/catalog/cars/01). 
By the way, in the Cloud version we can import collections with subfolders.

**Comment by jahidzaynal** [comment]
OK, I now get what you meant by dynamic parameters. While this is currently not possible in the desktop client, you can certainly do these kinds of tests using the more feature-full cloud version. And as you pointed out, the cloud version already supports subfolders when importing.

The desktop client is in very early stages and will hopefully catch-up, but for now if your needs are more than simple exploratory API calls and manual response validations, then I suggest you continue using the cloud offering which will do all these for you.

Closing this issue now as I believe the questions have been answered. If you do have any more questions please feel free to reach us again :)
